### ISSUE TITLE
Funksjonen er nå i Tripletex

### ISSUE THREAD

**Issue by OscarKolsrud** [omelhus/TripletexBrreg#1]
Til info:

Denne funksjonen er nå bygget inn i tripletex. Muligens behov for å endre beskrivelse/merke abandoned?

**Comment by OscarKolsrud** [comment]
Beklager, leste ikke godt nok :)

**Comment by omelhus** [comment]
Hei! 

Jeg er enig i at readme bør oppdateres ja! Det er jo ikke noe Brønnøysund igjen i scriptet lenger, og resten vet jeg ikke om fungerer.

Takk for at du er engasjert!
